/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package microarch.delivery.adapters.in.http.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import microarch.delivery.adapters.in.http.model.Error;
import microarch.delivery.adapters.in.http.model.Location;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.UUID;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-20T14:50:53.620457041+03:00[Europe/Moscow]")
@Validated
@Tag(name = "MoveCourier", description = "the MoveCourier API")
public interface MoveCourierApi {

    /**
     * POST /api/v1/couriers/{courierId}/move : Переместить курьера
     * Позволяет переместить курьера
     *
     * @param courierId Идентификатор курьера (required)
     * @param location Местоположение (required)
     * @return Успешный ответ (status code 200)
     *         or Некорректные параметры запроса (status code 400)
     *         or Конфликт при завершении заказа (status code 409)
     *         or Внутренняя ошибка сервиса (status code 500)
     */
    @Operation(
        operationId = "moveCourier",
        summary = "Переместить курьера",
        description = "Позволяет переместить курьера",
        tags = { "MoveCourier" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Некорректные параметры запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Конфликт при завершении заказа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервиса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/couriers/{courierId}/move",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> moveCourier(
        @Parameter(name = "courierId", description = "Идентификатор курьера", required = true, in = ParameterIn.PATH) @PathVariable("courierId") UUID courierId,
        @Parameter(name = "Location", description = "Местоположение", required = true) @Valid @RequestBody Location location
    );

}
